# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
