# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Track Name')),
                ('short_description', models.TextField(max_length=255, verbose_name='Short Description')),
                ('image', models.ImageField(upload_to=b'tracks')),
                ('courses', models.ManyToManyField(to='course_overviews.CourseOverview')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Degree Track',
                'verbose_name_plural': 'Degree Tracks',
            },
        ),
    ]
