# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreetrack',
            name='courses',
            field=models.ManyToManyField(db_constraint=False, to='course_overviews.CourseOverview'),
        ),
    ]
