# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_track', '0003_auto_20181110_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='image_url',
            field=models.CharField(default='/asset-v1:ibec+CS108+2018_T2+type@asset+block@Logo-MCE.png', max_length=255),
            preserve_default=False,
        ),
    ]
