# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_track', '0004_degree_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='short_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
