# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degree_track', '0005_degree_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Objective')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Objective number')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_track.Degree')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': 'Course Objective',
                'verbose_name_plural': 'Course Objectives',
            },
        ),
        migrations.CreateModel(
            name='ObjectivePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255, verbose_name='Objective point')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_track.CourseObjective')),
            ],
            options={
                'ordering': ('point',),
                'verbose_name': 'Objective Point',
                'verbose_name_plural': 'Objective Points',
            },
        ),
    ]
