# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_track', '0006_courseobjective_objectivepoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectivepoint',
            options={'ordering': ('pointn',), 'verbose_name': 'Objective Point', 'verbose_name_plural': 'Objective Points'},
        ),
        migrations.RenameField(
            model_name='objectivepoint',
            old_name='point',
            new_name='pointn',
        ),
    ]
