# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20181026_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
